function(manage_dependency_glad)

FetchContent_Declare(
	glad
	EXCLUDE_FROM_ALL
	GIT_REPOSITORY https://github.com/Dav1dde/glad.git
	GIT_TAG 73db193f853e2ee079bf3ca8a64aa2eaf6459043 # v2.0.8
	SOURCE_SUBDIR cmake
)
FetchContent_MakeAvailable(glad)

mark_as_advanced(FORCE
	FETCHCONTENT_UPDATES_DISCONNECTED_GLAD
	FETCHCONTENT_SOURCE_DIR_GLAD
	GLAD_SOURCES_DIR
) 
set(GLAD_AUTOGENERATED_DIR ${PROJECT_SOURCE_DIR}/external/glad-autogenerated)
glad_add_library(glad STATIC EXCLUDE_FROM_ALL
	REPRODUCIBLE QUIET
	LOCATION ${GLAD_AUTOGENERATED_DIR}
	API gl:core=4.5
)
target_include_directories(glad INTERFACE
	$<BUILD_INTERFACE:${GLAD_AUTOGENERATED_DIR}/include/glad>
	$<INSTALL_INTERFACE:glad>
)

endfunction()
