include(${CMAKE_SOURCE_DIR}/cmake/add_module_target.cmake RESULT_VARIABLE status)
if(status)
	message(STATUS "cmake add_module_target script found")
else()
	message(SEND_ERROR "add_module_target.cmake script not found.")
endif()

add_subdirectory(definitions)
add_subdirectory(effect)
add_subdirectory(injection)
add_subdirectory(input)
add_subdirectory(program)
add_subdirectory(pugi)
add_subdirectory(raudio)
add_subdirectory(render)
add_subdirectory(renderables)
add_subdirectory(sdl)
add_subdirectory(sound)
add_subdirectory(timer)

