add_subdirectory(definitions)
add_subdirectory(effect)
add_subdirectory(injection)
add_subdirectory(input)
add_subdirectory(program)
add_subdirectory(pugi)
add_subdirectory(raudio)
add_subdirectory(render)
add_subdirectory(renderables)
add_subdirectory(sdl)
add_subdirectory(sound)
add_subdirectory(timer)

