add_subdirectory(chessboard)
add_subdirectory(fire)
add_subdirectory(gradient)
add_subdirectory(plasma)
add_subdirectory(random_noise)
add_subdirectory(solid)
add_subdirectory(stars)
add_subdirectory(tunnel)
add_subdirectory(wheel)

add_module(effects
	DEPENDENCIES
	chessboard
	fire
	gradient
	plasma
	noise
	solid
	stars
	tunnel
	wheel
)
